### ISSUE TITLE
Typo in example probabilities

### ISSUE THREAD

**Issue by iimog** [Abhimanyu08/blog#2]
Hi Abhimanyu,

thanks for the great explanation of label smoothing. I found a little typo. At the end of section 1 you write:

> Now suppose our model didn't output ${p_{1}}$ but ${p_{2}=[0.01,0.79,0.15,0.5]}$. In this case it is less sure that the image has label 2. Loss will be ${L(y^{l},p_{2})= -(0.05\log0.01+0.85\log0.79+0.05\log0.15+0.05\log0.5)=0.56}$ which is less than the loss with ${p_{1}}$ ! This goes on to show that smooth labels want the model to be confident about it's predictions but not over-confident.

The problem with `p_2` is that the entries don't sum to 1. The last probability should likely be `0.05` instead of `0.5`. In this case the resulting loss is `0.68`. This in turn is slightly more than the loss for `p_1` (`0.61`) which matches my expectation.

Thanks again for a great tutorial!

**Comment by Abhimanyu08** [comment]
Thanks a lot Markus !!
